### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by hcferguson** [nmearl/specviz#111]
Getting an installation error when I try to install the latest pyfocal. Here's the traceback...

```
pip install -r requirements.txt
Collecting git+https://github.com/nmearl/astropy.git (from -r requirements.txt (line 3))
  Cloning https://github.com/nmearl/astropy.git to /var/folders/mq/rhncd1r10d37pb418hyq0hj80000gn/T/pip-lrcocbzf-build
Obtaining file:///Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/pyfocal (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.6.0 in /Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages (from astropy==1.1.dev14590->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages (from Pyfocal==0.1a1->-r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): pyqtgraph in /Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages (from Pyfocal==0.1a1->-r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): scipy in /Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages (from Pyfocal==0.1a1->-r requirements.txt (line 4))
Installing collected packages: astropy, Pyfocal
  Found existing installation: astropy 1.1.1
    Uninstalling astropy-1.1.1:
      Successfully uninstalled astropy-1.1.1
  Running setup.py install for astropy ... error
    Complete output from command /Users/hcferguson/anaconda/envs/pyf_env/bin/python -u -c "import setuptools, tokenize;__file__='/var/folders/mq/rhncd1r10d37pb418hyq0hj80000gn/T/pip-lrcocbzf-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/mq/rhncd1r10d37pb418hyq0hj80000gn/T/pip-ko5pzref-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running pre_hook from astropy._erfa.setup_package for build_py command
    pre_build_py_hook command hook build_py raised an exception: %s
    
    Traceback (most recent call last):
      File "/private/var/folders/mq/rhncd1r10d37pb418hyq0hj80000gn/T/pip-lrcocbzf-build/astropy_helpers/astropy_helpers/setup_helpers.py", line 289, in run_command_hooks
        hook_obj(cmd_obj)
      File "astropy/_erfa/setup_package.py", line 24, in pre_build_py_hook
        preprocess_source()
      File "astropy/_erfa/setup_package.py", line 85, in preprocess_source
        verbose=False)
      File "astropy/_erfa/erfa_generator.py", line 359, in main
        from jinja2 import Environment, FileSystemLoader
    ImportError: No module named 'jinja2'
    
    
    ----------------------------------------
  Rolling back uninstall of astropy
Command "/Users/hcferguson/anaconda/envs/pyf_env/bin/python -u -c "import setuptools, tokenize;__file__='/var/folders/mq/rhncd1r10d37pb418hyq0hj80000gn/T/pip-lrcocbzf-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/mq/rhncd1r10d37pb418hyq0hj80000gn/T/pip-ko5pzref-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /var/folders/mq/rhncd1r10d37pb418hyq0hj80000gn/T/pip-lrcocbzf-build
```

**Comment by pllim** [comment]
`jinja2` comes with Anaconda, you just need to install it with this command:

```
conda install jinja2
```

**Comment by nmearl** [comment]
Yes, this seems to be a thing with having to switch to the dev version of astropy. I can stick it into the pip requirements for now, and we can remove it later.

**Comment by nmearl** [comment]
Added in 0c6dc0d5f4e83e35afea3dc5828dbc981d0f52ba.
